import { ThemeColorSet } from '@/types';

export const themePresets: Record<string, { light: ThemeColorSet; dark: ThemeColorSet }> = {
  'fantasy-parchment': {
    light: {
      surface: '#fff8f0',
      surfaceDim: '#f0d991',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#fff3d5',
      surfaceContainer: '#ffedba',
      surfaceContainerHigh: '#fbf2cd',
      surfaceContainerHighest: '#f7e1a0',
      primary: '#8d34b4',
      primaryContainer: '#e8aaff',
      primaryDim: '#8025a6',
      onSurface: '#3e3101',
      outlineVariant: '#c4b174',
      secondary: '#954b00',
      secondaryContainer: '#ffdcc5',
      onSecondaryContainer: '#814000',
      tertiary: '#2d6a4f',
      tertiaryContainer: '#beffdc',
    },
    dark: {
      surface: '#2c2317',
      surfaceDim: '#1e170d',
      surfaceContainerLowest: '#110b05',
      surfaceContainerLow: '#221910',
      surfaceContainer: '#302519',
      surfaceContainerHigh: '#3c2f21',
      surfaceContainerHighest: '#473a2b',
      primary: '#d59df4',
      primaryContainer: '#67168c',
      primaryDim: '#b17ad2',
      onSurface: '#f5eedd',
      outlineVariant: '#6e6242',
      secondary: '#ffb68c',
      secondaryContainer: '#632d00',
      onSecondaryContainer: '#ffdcc5',
      tertiary: '#72d6a4',
      tertiaryContainer: '#0e4a30',
    }
  },
  'gothic-horror': {
    light: {
      surface: '#fffcfc',
      surfaceDim: '#ecdcdc',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#f8eeee',
      surfaceContainer: '#f0dfdf',
      surfaceContainerHigh: '#e8d2d2',
      surfaceContainerHighest: '#dec3c3',
      primary: '#8b0000',
      primaryContainer: '#ffccd5',
      primaryDim: '#6a0000',
      onSurface: '#2a1a1a',
      outlineVariant: '#a38484',
      secondary: '#4a2525',
      secondaryContainer: '#ffdad6',
      onSecondaryContainer: '#410002',
      tertiary: '#414941',
      tertiaryContainer: '#c2f0c2',
    },
    dark: {
      surface: '#121212',
      surfaceDim: '#0a0a0a',
      surfaceContainerLowest: '#050505',
      surfaceContainerLow: '#1a1a1a',
      surfaceContainer: '#242424',
      surfaceContainerHigh: '#2e2e2e',
      surfaceContainerHighest: '#383838',
      primary: '#d32f2f',
      primaryContainer: '#7a0010',
      primaryDim: '#ff8a80',
      onSurface: '#d4c5b9',
      outlineVariant: '#4d453e',
      secondary: '#dfbdaf',
      secondaryContainer: '#53433e',
      onSecondaryContainer: '#ffdad0',
      tertiary: '#a2bfa2',
      tertiaryContainer: '#1c3520',
    }
  },
  'cyberpunk': {
    light: {
      surface: '#ffffff',
      surfaceDim: '#f0f0f3',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#f4f4f7',
      surfaceContainer: '#eaeaf0',
      surfaceContainerHigh: '#dedee8',
      surfaceContainerHighest: '#cfcfdd',
      primary: '#bc34fa',
      primaryContainer: '#f5d6ff',
      primaryDim: '#a112df',
      onSurface: '#05050a',
      outlineVariant: '#9c9cb4',
      secondary: '#005b94',
      secondaryContainer: '#e0f3ff',
      onSecondaryContainer: '#001c33',
      tertiary: '#00875a',
      tertiaryContainer: '#d3ffef',
    },
    dark: {
      surface: '#05050a',
      surfaceDim: '#000002',
      surfaceContainerLowest: '#000000',
      surfaceContainerLow: '#0e0e17',
      surfaceContainer: '#171724',
      surfaceContainerHigh: '#232333',
      surfaceContainerHighest: '#313144',
      primary: '#bc34fa',
      primaryContainer: '#6b009c',
      primaryDim: '#e8a3ff',
      onSurface: '#3bfb90',
      outlineVariant: '#414158',
      secondary: '#00d2ff',
      secondaryContainer: '#004d61',
      onSecondaryContainer: '#bfeeff',
      tertiary: '#ff54b0',
      tertiaryContainer: '#66003a',
    }
  },
  'space-scifi': {
    light: {
      surface: '#f8f9fa',
      surfaceDim: '#e9ecef',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#f1f3f5',
      surfaceContainer: '#e9ecef',
      surfaceContainerHigh: '#dee2e6',
      surfaceContainerHighest: '#ced4da',
      primary: '#00b4d8',
      primaryContainer: '#caf0f8',
      primaryDim: '#0077b6',
      onSurface: '#03045e',
      outlineVariant: '#90e0ef',
      secondary: '#0096c7',
      secondaryContainer: '#ade8f4',
      onSecondaryContainer: '#023e8a',
      tertiary: '#48cae4',
      tertiaryContainer: '#caf0f8',
    },
    dark: {
      surface: '#0d1117',
      surfaceDim: '#010409',
      surfaceContainerLowest: '#010204',
      surfaceContainerLow: '#161b22',
      surfaceContainer: '#21262d',
      surfaceContainerHigh: '#30363d',
      surfaceContainerHighest: '#484f58',
      primary: '#00d2ff',
      primaryContainer: '#003543',
      primaryDim: '#5ce1ff',
      onSurface: '#e6edf3',
      outlineVariant: '#30363d',
      secondary: '#00796b',
      secondaryContainer: '#004d40',
      onSecondaryContainer: '#80cbc4',
      tertiary: '#0288d1',
      tertiaryContainer: '#01579b',
    }
  },
  'whimsical': {
    light: {
      surface: '#faf5ff',
      surfaceDim: '#eedeff',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#f5e8ff',
      surfaceContainer: '#ebd5ff',
      surfaceContainerHigh: '#dfbeff',
      surfaceContainerHighest: '#cca0ff',
      primary: '#2d6a4f',
      primaryContainer: '#d8f3dc',
      primaryDim: '#1b4332',
      onSurface: '#2d174d',
      outlineVariant: '#b39ddb',
      secondary: '#7b2cbf',
      secondaryContainer: '#e0aaff',
      onSecondaryContainer: '#3c096c',
      tertiary: '#40916c',
      tertiaryContainer: '#b7e4c7',
    },
    dark: {
      surface: '#1d0a2d',
      surfaceDim: '#11031d',
      surfaceContainerLowest: '#0a0014',
      surfaceContainerLow: '#26123b',
      surfaceContainer: '#31194b',
      surfaceContainerHigh: '#3e225c',
      surfaceContainerHighest: '#4b2b6d',
      primary: '#68d391',
      primaryContainer: '#1c4d2f',
      primaryDim: '#9ae6b4',
      onSurface: '#faf5ff',
      outlineVariant: '#4f3a6b',
      secondary: '#c77dff',
      secondaryContainer: '#5a189a',
      onSecondaryContainer: '#e0aaff',
      tertiary: '#9ae6b4',
      tertiaryContainer: '#1c4d2f',
    }
  },
  'gritty': {
    light: {
      surface: '#e5e5e5',
      surfaceDim: '#cccccc',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#f0f0f0',
      surfaceContainer: '#e0e0e0',
      surfaceContainerHigh: '#d4d4d4',
      surfaceContainerHighest: '#c8c8c8',
      primary: '#c05621',
      primaryContainer: '#ffedd5',
      primaryDim: '#7c2d12',
      onSurface: '#1c1c1c',
      outlineVariant: '#a3a3a3',
      secondary: '#4b5563',
      secondaryContainer: '#f3f4f6',
      onSecondaryContainer: '#1f2937',
      tertiary: '#374151',
      tertiaryContainer: '#e5e7eb',
    },
    dark: {
      surface: '#2d2d2d',
      surfaceDim: '#1f1f1f',
      surfaceContainerLowest: '#121212',
      surfaceContainerLow: '#252525',
      surfaceContainer: '#353535',
      surfaceContainerHigh: '#404040',
      surfaceContainerHighest: '#4c4c4c',
      primary: '#f6ad55',
      primaryContainer: '#7c2d12',
      primaryDim: '#dd6b20',
      onSurface: '#eaeaea',
      outlineVariant: '#575757',
      secondary: '#9ca3af',
      secondaryContainer: '#374151',
      onSecondaryContainer: '#f3f4f6',
      tertiary: '#d1d5db',
      tertiaryContainer: '#4b5563',
    }
  },
  'heroic': {
    light: {
      surface: '#fffdf5',
      surfaceDim: '#f5edd0',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#faf6e5',
      surfaceContainer: '#f2edd3',
      surfaceContainerHigh: '#eadebe',
      surfaceContainerHighest: '#e0cca5',
      primary: '#0a2342',
      primaryContainer: '#d0e1fd',
      primaryDim: '#00142b',
      onSurface: '#1a1a1a',
      outlineVariant: '#cbb685',
      secondary: '#2f5d62',
      secondaryContainer: '#a7beb5',
      onSecondaryContainer: '#0a2342',
      tertiary: '#5e8b7e',
      tertiaryContainer: '#dfeeea',
    },
    dark: {
      surface: '#0d1b2a',
      surfaceDim: '#040b14',
      surfaceContainerLowest: '#020508',
      surfaceContainerLow: '#152639',
      surfaceContainer: '#1b2d42',
      surfaceContainerHigh: '#243a54',
      surfaceContainerHighest: '#2f4868',
      primary: '#ffd700',
      primaryContainer: '#4a3b00',
      primaryDim: '#e5c100',
      onSurface: '#e0e1dd',
      outlineVariant: '#3c5a75',
      secondary: '#415a77',
      secondaryContainer: '#1d2d44',
      onSecondaryContainer: '#e0e1dd',
      tertiary: '#778da9',
      tertiaryContainer: '#31445c',
    }
  }
};

export function getThemeStyles(preset: string, custom?: { light?: ThemeColorSet; dark?: ThemeColorSet }): string {
  const chosen = themePresets[preset] || themePresets['fantasy-parchment'];
  
  const light = { ...chosen.light, ...(custom?.light || {}) };
  const dark = { ...chosen.dark, ...(custom?.dark || {}) };

  const formatVariables = (colors: ThemeColorSet) => {
    return Object.entries(colors)
      .map(([key, value]) => {
        // Convert camelCase key to CSS variable format: surfaceDim -> --surface-dim
        const cssKey = key.replace(/([A-Z])/g, '-$1').toLowerCase();
        return `  --${cssKey}: ${value};`;
      })
      .join('\n');
  };

  return `
:root {
${formatVariables(light)}
}

.dark {
${formatVariables(dark)}
}
  `.trim();
}
